### PR TITLE
Niak 50

### PR DESCRIPTION
**Pull request by majchrow**
This one is important, lets fix everything before merging.

- ~~Why do we need to "@Overwrite" [here](https://github.com/niewidoczni-akademicy/rezerwacje-sal/blob/develop/rezerwacje-app/src/main/java/org/niewidoczniakademicy/rezerwacje/dao/repository/RecruitmentPeriodRepository.java#L11) (and in the UserRepository). I deleted it from both User and Recruitments + deleted unnecessary null check in UserService. (to clarify)~~
-  ~~Change controllers to be consistent - either  return ResponseEntity.ok().body(response); or return new ResponseEntity<>(response, HttpStatus.OK); or even ResponseStatus as annotation, just choose one style for all.~~
-  ~~Do we really need to return List/Long wrapped with Response object with one attribute. Isn't it overkill there? 90 % of our Rest Models consist of only one attribute (open for discussion)~~
-  ~~Is the structure good, any feedback would be great here (open for discussion)~~
- ~~Check all parts of the backend that you are responsible for, to make sure that the requests are passing before merge.  (todo)~~

UPDATE: RESOLVED

### CODE REVIEW

**Comment by majchrow** [comment]
> This one is important, lets fix everything before merging.
> 
>     * Why do we need to "@overwrite" [here](https://github.com/niewidoczni-akademicy/rezerwacje-sal/blob/develop/rezerwacje-app/src/main/java/org/niewidoczniakademicy/rezerwacje/dao/repository/RecruitmentPeriodRepository.java#L11) (and in the UserRepository). I deleted it from both User and Recruitments + deleted unnecessary null check in UserService. (to clarify)
> 
>     * Change controllers to be consistent - either  return ResponseEntity.ok().body(response); or return new ResponseEntity<>(response, HttpStatus.OK); or even ResponseStatus as annotation, just choose one style for all. (todo)
> 
>     * Do we really need to return List/Long wrapped with Response object with one attribute. Isn't it overkill there? 90 % of our Rest Models consist of only one attribute (open for discussion)
> 
>     * Is the structure good, any feedback would be great here (open for discussion)
> 
>     * Check all parts of the backend that you are responsible for, to make sure that the requests are passing before merge.  (todo)

As for point 2 (ResponseEntity) I would prefer 2 annotations 
@ResponseBody + @ResponseStatus(value = HttpStatus.OK) (or any status here)
then we could drop all the ResponseEntity occurance from our Https Methods. 
(If I'm now mistaken all 3 approach should be equivalent)

I've done initial commits for [controller](https://github.com/niewidoczni-akademicy/rezerwacje-sal/pull/19/commits/89790ce2243564c488dce49086dc6c2d45608ff7) and [error](https://github.com/niewidoczni-akademicy/rezerwacje-sal/pull/19/commits/7a95331e795f69c4d34a875386a81e39ed0108f0) responses just to show what is my point of view. Please check if this structure suit you, if not I will revert changes.

**Comment by jakubowiczish** [comment]
I'm kinda used to static methods from ResponseEntity, for instance 
```java
return ResponseEntity.status(HttpStatus.OK).body(something);
```
But it's ok for me

**Comment by jakubowiczish** [comment]
In terms of usage of only one attribute in response model, I would leave it as it is. In my opinion, it's more consistent and concise.

**Comment by jfoder** [comment]
> In terms of usage of only one attribute in response model, I would leave it as it is. In my opinion, it's more consistent and concise.

And later we can add some annotations to generate API description. I don't know if it can be done without separate models.

**Pull request merged**
